### ISSUE TITLE
Improvement Request:  Image scaling on HiDPI display

### ISSUE THREAD

**Issue by finalpatch** [emacs-slack/emacs-slack#464]
**Describe the bug**

This is not a bug report but rather an improvement request.

Right now on high density Mac screens, all images displayed by emacs-slack are low-res. 

I have managed to hack just a few functions to display them in hi-res on my laptop:

```
  (cl-defun slack-image--create (path &key (width nil) (height nil) (max-height nil) (max-width nil))
  (let* ((imagemagick-available-p (image-type-available-p 'imagemagick))
         (image (apply #'create-image (append (list path (and imagemagick-available-p 'imagemagick) nil)
                                              (list :scale 0.5)  ; <- add scale
                                              (if height (list :height height))
                                              (if width (list :width width))
                                              (if max-height
                                                  (list :max-height max-height))
                                              (if max-width
                                                  (list :max-width max-width))))))
    (if (and (display-graphic-p) imagemagick-available-p)
        (slack-image-shrink image max-height)
      image)))
  ;---
  (cl-defun slack-user-image (user team &optional (size 72)) <- double requested size
  (when user
    (let ((image (slack-user-fetch-image user size team)))
      (when image
        (create-image image nil nil :ascent 80 :scale 0.5))))) ; <- add scale
```

If you are going to implement this, you might want to add a customization option so users could choose to enable this.

**To Reproduce**

Run emacs-slack on Retina display Macbook Pro
Observe all preview images, profile images are low-res (half resolution)

**Backtrace**
```
Paste Backtrace if any.
Do not forget to mask confidential information. (e.g. token, message, ...)
```

**Expected behavior**

**Screenshots**

**Environment:**
 - OS: [e.g. macOS]
 - Emacs Version: [e.g. 25]
 - emacs-slack Version: [e.g. `9ffc86` (commit hash) or `20190519.716` (melpa version)]

**Additional context**

**Comment by ag91** [comment]
mmm, in my testing this makes the message buffer images smaller due to the scaling.
I think this should rather be a setting depending on the quality of your screen, but I am not sure is worth adding for now.
Feel free to reopen with a PR ;)
