### ISSUE TITLE
org-store-link support

### ISSUE THREAD

**Issue by matthew-piziak** [emacs-slack/emacs-slack#475]
Hi @yuya373! Do you use Org mode? It would be great to have `org-store-link` support for Slack buffers.

Desired Behavior:
1. User runs `org-store-link` (usually `C-c l`) with point over a message.
2. User navigates to an Org file (or invokes an Org capture) and runs `org-insert-link` (usually `C-c C-l`). 
3. User clicks the link, which opens the appropriate Slack room and scrolls to the appropriate message.

Current behavior:
1. Running `org-store-link` throws `user-error: No method for storing a link from this buffer`

One way to implement this would be if `emacs-slack` itself had a way of opening Slack links, as produced by `slack-message-copy-link`. I understand that opening the buffer at the appropriate message may be challenging.

Thank you!

**Comment by matthew-piziak** [comment]
Examples of custom Org link types:
- man pages: https://orgmode.org/manual/Adding-hyperlink-types.html
- dired mode: https://emacs.stackexchange.com/questions/13093/get-org-link-to-insert-link-description-automatically

For example, if `emacs-slack` could handle message links, the appropriate custom link type could be defined as an advice around `org-store-link`.

**Comment by matthew-piziak** [comment]
Something like this is a start
```
(defun org-slack-store-link ()
  (when (derived-mode-p 'slack-mode)
    (let ((slack-buffer (buffer-name)))
      (org-store-link-props
       :type "slack"
       :link (format "slack:%s" slack-buffer)
       :description slack-buffer))))
(org-link-set-parameters "slack" :follow 'switch-to-buffer :store 'org-slack-store-link)
```
But there's probably a better function to use than `switch-to-buffer`.

**Comment by ag91** [comment]
Abemus links! I came up with a first working implementation of ol-emacs-link: the code [here](https://github.com/ag91/ol-emacs-slack)  and a blog post describing a bit more in detail [here](https://ag91.github.io/blog/2020/09/12/org-mode-links-for-emacs-slack/). Let me know for issues.

**Comment by symbiont-matthew-piziak** [comment]
@ag91 This works perfectly. Thank you!

**Comment by matthew-piziak** [comment]
@ag91 Ah, except that it does not seem to work for thread buffers.

**Comment by ag91** [comment]
@matthew-piziak thanks! And thanks for reporting that issue. I shall fix that soon :)

**Comment by ag91** [comment]
Actually are you taking from master https://github.com/ag91/ol-emacs-slack/? I received a contribution just about that earlier. If not, can you tell me the step to reproduce in an issue there?

**Comment by symbiont-matthew-piziak** [comment]
@ag91 I am using the 24 Sep 2020 version, yes. 
To reproduce:
1. Invoke `org-store-link` in a thread buffer.
2. Invoke `org-insert-link` in an Org buffer.
3. Invoke `org-open-at-point` on the link.
4. Observe that you are now in the _parent_ channel, rather in the thread.

Similarly, the link only points to a channel for me, not to a specific message within that channel.

**Comment by matthew-piziak** [comment]
@ag91 I am using the 24 Sep 2020 version.

To reproduce:
1. Invoke org-store-link in a thread buffer.
2. Invoke org-insert-link in an Org buffer.
3. Invoke org-open-at-point on the link.
4. Observe that you are now in the parent channel, rather in the thread.

Also, the link only points to a channel for me, not to a specific message within that channel, but as far as I can tell the latter behavior was never intended.

**Comment by ag91** [comment]
@matthew-piziak finally managed to add support for threads and specific channels: https://ag91.github.io/blog/2022/04/01/ol-emacs-slack-added-support-for-thread-links/

**Comment by matthew-piziak** [comment]
@ag91 Weird, it fails for me.

```
Debugger entered--Lisp error: (void-variable name)
  ol/slack-store-link()
  org-store-link(nil 1)
  funcall-interactively(org-store-link nil 1)
  command-execute(org-store-link)
```

**Comment by ag91** [comment]
mmm very strange, somebody had the same problem but I cannot reproduce on my side: https://github.com/ag91/ol-emacs-slack/issues/5

Can you try `(oref (slack-buffer-team slack-current-buffer) name)` in the buffer you are trying to store a link in? It should show your team name and I think that is where it fails.

**Comment by matthew-piziak** [comment]
It does show my team name, without failing.

**Comment by ag91** [comment]
so if you run `(ol/slack-store-link)` you get the same error? I hope the error is in my function and not in its integration with org-link..

**Comment by matthew-piziak** [comment]
@ag91 Yep, same error:
```
Debugger entered--Lisp error: (void-variable name)
  ol/slack-store-link()
  eval-expression((ol/slack-store-link) nil nil 127)
  funcall-interactively(eval-expression (ol/slack-store-link) nil nil 127)
  command-execute(eval-expression)
  ```

**Comment by ag91** [comment]
I will probably merge the projects, but there is support. @matthew-piziak open an issue in the other repo if you are still unable to use it
