### ISSUE TITLE
Only one chance to get password correct

### ISSUE THREAD

**Issue by ghost** [emacs-slack/emacs-slack#513]
Here's my configuration:

```
(use-package! slack
  :commands (slack-start)
  :init
  (setq slack-buffer-emojify t) ;; if you want to enable emoji, default nil
  (setq slack-prefer-current-team t)
  :config
  (slack-register-team
   :name "dummy-name"
   :default t
   :token (password-store-get "dummy-token-name")
   :subscribed-channels '(dummy-channel)
   :full-and-display-names t))
```

It seems reasonable to use `password-store` to lookup the token, rather than leaving it in plaintext. However, this only works if I type the password correctly on the first try. If I fail to do that, a second call to `slack-register-team` or `slack-start` presents the following error:

```
cl-generic-ensure-function: slack-team-connect is already defined as something else than a generic function
```

**Comment by pcrama** [comment]
Just in case this helps someone with the same problem: as a work around, I `M-: (fmakunbound 'slack-team-connect)` before `M-x slack-start`ing a second time, and try not to mess up my password the second time.

**Comment by ag91** [comment]
you can also set the passwords via
```
(oset slack-current-team token "xxx")
(oset slack-current-team cookie "xxx")
```
you can use `slack-refresh-token` for working that around, since it shows you these snippets.
