### ISSUE TITLE
slack-insert-emoji: wrong-number-of-arguments with helm

### ISSUE THREAD

**Issue by chasecaleb** [emacs-slack/emacs-slack#517]
**Describe the bug**
Error when attempting to do `slack-insert-emoji` while `helm-mode` is enabled. If I disable `helm-mode` and enable `ido-mode` I do not have an issue. [This is the line in helm (permalink)](https://github.com/emacs-helm/helm/blob/c156260c1e8421b79cf723304ee555316687db9c/helm-mode.el#L1572) that it is blowing up on - helm only provides your predicate with a single arg instead of two. I'm not familiar enough with any of the libraries involved (slack, emojify, or helm) to know where the bug lies, so I thought I would start with an issue here. I don't mind filing an issue with a different project if you want me to, or you can as well.

Note: My Slack workspace a moderate amount custom emojis, but I'm guessing that doesn't have anything to do with that. I'm open to trying with a different workspace if you think that's relevant and can suggest one for me to join and test against.

**To Reproduce**
1. Enable `helm-mode`
1. Open a slack channel
1. Invoke `slack-insert-emoji`
1. Type any character
1. Error

**Backtrace**
Too big to fit in character limit and I couldn't quickly figure out a way to truncate lines, so I put it in a gist: https://gist.github.com/chasecaleb/6f11c36b60192c7b62293781f7fb6ed2

**Expected behavior**
Inserting an emoji should work with helm just like it does with ido.

**Environment:**
- OS: Arch Linux
- Emacs version: 26.3 with `system-configuration-features` = `XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2`
- emacs-slack version: current master - `d53a57a18fb7034182c3d02503f937761e6a2a64`
- emacs-emojify version: current master - `20d4fc0ea45a53f7edbe99c83317a3e048e398ef`
- emacs-helm version: couple days old master - `c156260c1e8421b79cf723304ee555316687db9c`

**Comment by maurelio1234** [comment]
Hi,

I have the same problem when using ivy.

My environment:

- OS: Ubuntu 18.04
- Emacs 27.0.91:  "XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER LCMS2 GMP"
- emacs-slack: a6d9f49
- emacs-emojify: dfa3c6d

https://gist.github.com/maurelio1234/69986f5c76ebcc7dec7af81a34bfac25

I can reproduce it when I try to `(slack-message-add-reaction)` on any slack buffer.

There goes a stack trace when I do `(slack-select-emoji slack-current-team)` : 

https://gist.github.com/maurelio1234/69986f5c76ebcc7dec7af81a34bfac25

**Comment by maurelio1234** [comment]
BTW, when I look at latest emacs-emojify commits I wonder if it comes from there:

```
dfa3c6d master origin/master Whoops; forgot to remove this…
194741e Revert this back to `completing-read`.
```

They are kind of related to that...

**Comment by maurelio1234** [comment]
I have a temporary fix/explanation for that here:

https://github.com/maurelio1234/emacs-slack/commit/4f1899e3f5e034054489da19e577726c02cf330a

I'm not sure that is a solution yet, but at least it got reactions working again on my computer...

**Comment by powellc** [comment]
Been a while, but I can confirm that this fixes the issue. Any chance of upstreaming this with a PR or some such @maurelio1234 ?

**Comment by erichlf** [comment]
This also fixes the same sort of issue with `slack-message-add-reaction`.

**Comment by maurelio1234** [comment]
Hi, I will transform it on a PR to see what happens.

**Comment by maurelio1234** [comment]
I have just created the PR, let's wait for some reaction from the maintainer on how to proceed on this.

**Comment by ag91** [comment]
this should be fixed in the latest version
