### ISSUE TITLE
Tracking behavior for threads and reactions

### ISSUE THREAD

**Issue by chasecaleb** [emacs-slack/emacs-slack#519]
Currently, all new messages in threads are added to tracking list if `slack-buffer-create-on-notify` is non-nil. Would you be open to adding a config option that would make it work like alerts, which only show for _followed_ threads? I'm willing to make a PR if that helps.

Here's the kludgy way that I accomplished it with an advice:

```emacs-lisp
(defun cc/slack-thread-message-update-advice (fn this room team replace)
  "Advice to prevent opening/tracking threads that are not followed."
  (let ((slack-buffer-create-on-notify
         (and slack-buffer-create-on-notify
              (slack-message-subscribed-thread-message-p this room))))
    (funcall fn this room team replace)))
(advice-add 'slack-thread-message-update-buffer :around 'cc/slack-thread-message-update-advice)
```

**Comment by chasecaleb** [comment]
After a little more investigation, it looks like my advice only half works. It prevents the thread from becoming tracked, but the room containing the thread is still tracked *if* the room is not open and `slack-buffer-create-on-notify` is non-nil.

I'm having a really hard time wrapping my head around what's going on due to the size and complexity of this package. Ideally I would like the following behavior, regardless of what buffers are already open:
* New message in a thread I am not following: do nothing
* New message in a followed thread: add the thread to tracking list but do not add the containing room
* Reaction to anything: do nothing

Can you point me in the right direction to accomplish this? I know that functions can be added `tracking-ignored-buffers` from `tracking.el`, which might be a better way. However the function is only provided the buffer as an argument, and I can't figure out how to get the right information there.

**Comment by ag91** [comment]
@chasecaleb I think I tweaked those in the latest emacs-slack version, could you reopen if this is still not solved?
