### ISSUE TITLE
Emojis: default slack emojis (slack-emoji-master) are missing

### ISSUE THREAD

**Issue by chasecaleb** [emacs-slack/emacs-slack#520]
**Describe the bug**
`emojify-user-emojis` contains team-specific emojis from `(oref team emoji-master)` but does not have the default/built-in emojis from `slack-emoji-master`.

Team emojis are added to `emojify-user-emojis` here, within `slack-download-emoji`:
https://github.com/yuya373/emacs-slack/blob/d53a57a18fb7034182c3d02503f937761e6a2a64/slack-emoji.el#L58-L62

Whereas there is no equivalent logic in `slack-emoji-fetch-master-data` (but there should be):
https://github.com/yuya373/emacs-slack/blob/d53a57a18fb7034182c3d02503f937761e6a2a64/slack-emoji.el#L113-L133

**To Reproduce**
1. Open a slack room of any sort
1. M-x `slack-insert-emoji`
1. Type `:woman-shr` and attempt to complete (via tab or whatever, depending on your completion config)
1. Result: no matches, but it should complete to `:woman-shrugging:`

Alternative steps:
1. Open a slack room
1. Find or send a message containing `:woman-shrugging:` (type it out by hand, since `slack-insert-emoji` doesn't recognize it)
1. Result: `:woman-shrugging:` is incorrectly shown as text instead of replaced by an emoji

**Backtrace**
Not applicable

**Expected behavior**
Emojis from `slack-emoji-master` should be added to `emojify-user-emojis` so that they can be inserted via `slack-insert-emoji` as well as rendered as an image instead of text in messages.

**Environment:**
- OS: Arch Linux
- Emacs version: 26.3 with system-configuration-features = XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
- emacs-slack version: current master - d53a57a18fb7034182c3d02503f937761e6a2a64
- emacs-emojify version: current master - 20d4fc0ea45a53f7edbe99c83317a3e048e398ef

**Additional context**
This is a slight tangent, but I noticed that emojis are added with style `"github"`. Would it make sense to change it to e.g. `"slack"` instead? I think that would improve the UX since it would be more clear where the emojis are coming from, especially for people who use `emojify.el` for more than just slack.

**Comment by ag91** [comment]
> This is a slight tangent, but I noticed that emojis are added with style "github". Would it make sense to change it to e.g. "slack" instead? I think that would improve the UX since it would be more clear where the emojis are coming from, especially for people who use emojify.el for more than just slack.

This is not clear to me: there are only 3 styles, ascii, unicode and github. [These are aimed at how emojify displays emojis inline.](https://github.com/iqbalansari/emacs-emojify?tab=readme-ov-file#configuring-the-types-of-emojis-displayed)
Do you mean you don't want to see `github` in the completing read?

**Comment by ag91** [comment]
this is fixed in `bugfix/583-reduce-file-descriptors-consumptions-due-to-emoji`. I will wait tomorrow for merging it in, to see if others can test it (although it is super cool to have all emojis visible: thanks for the bug report!)

**Comment by ag91** [comment]
merged the fix, it is good to have more emojis :)
