### ISSUE TITLE
Support disabling displaying profile image

### ISSUE THREAD

**Issue by catern** [emacs-slack/emacs-slack#533]
To increase density of displayed text, and remove distracting images, it would be nice to be able to disable display of profile images/avatars.

**Comment by alexanderjamesking** [comment]
+1

**Comment by alexanderjamesking** [comment]
Looking at the history it seems a PR was rejected with this functionality: https://github.com/yuya373/emacs-slack/pull/505/files

I think it's a useful feature

**Comment by jsilve24** [comment]
I agree, would like a more compact representation.

**Comment by ag91** [comment]
made a defcustom slack-render-profile-images-p which works for all teams (as I guess users would not specify that per team)
