### ISSUE TITLE
Code Formatting Shows Up Mangled

### ISSUE THREAD

**Issue by erichlf** [emacs-slack/emacs-slack#534]
**Describe the bug**
When using multiple line code in a message the code formatting is mangled.

**To Reproduce**
1. Go to a direct message, channel, or group message.
2. Type \`\`\`formatted code\`\`\` and then hit enter
3. The resulting message you see has a mangled format.
4. Slack has the code formatted correctly.

**Expected behavior**
The code should appear formatted as it was typed.

**Screenshots**
* Formatting Displayed in Emacs 
![image](https://user-images.githubusercontent.com/1392578/93371013-a8546800-f81f-11ea-85d0-47c2de5454ca.png)
* Formatting Displayed in Slack
![image](https://user-images.githubusercontent.com/1392578/93371115-d76ad980-f81f-11ea-83bd-dc46124cf79f.png)

**Environment:**
 - OS: Ubuntu 20.04
 - Emacs Version: 26.3
 - emacs-slack Version: `20200830.1021`

**Comment by erichlf** [comment]
I had another issue with inline messages sent to me. The ticks came out as some weird '_'. 
* emacs-slack interpretation
![image](https://user-images.githubusercontent.com/1392578/93471066-d938a980-f8c0-11ea-8f1b-6e91a64bace1.png)
* slack message
![image](https://user-images.githubusercontent.com/1392578/93470975-ba3a1780-f8c0-11ea-908d-51c1504e6a87.png)

**Comment by ag91** [comment]
thanks for this, I need to fix it. Something on how markdown is interpreted here :)

**Comment by ag91** [comment]
I couldn't reproduce the underscore issue, but I fixed the mangled code :)
