### ISSUE TITLE
Feature request: Mentions & reactions

### ISSUE THREAD

**Issue by skybert** [emacs-slack/emacs-slack#537]
The feature I use the most in the official web client is [Mentions & reactions](https://www.howtogeek.com/668887/how-to-dock-slacks-mentions-reactions-screen-to-the-right-side-panel/), giving me a quick overview of whoever has mentioned me or reacted to one of my post. 

In `emacs-slack`, I would expect:
- a buffer with all posts mentioning me and showing my posts with reactions.
- either auto updated or updated whenever I hit `g` in it.
- possible to hit `RET` on any of these to jump to the appropriate chat buffer.

I've switched to `emacs-slack` as my primary client the last month and this `Mentions & reactions` feature is the only thing I really miss from the official client.

**Comment by togakangaroo** [comment]
so long as we're asking for stuff, any chance this buffer could show things across *all* groups you're in?

**Comment by benthamite** [comment]
I also miss this feature. What's the closest existing substitute? I rely heavily on `slack-select-unread-rooms`, but this will allow me to find a mention only among unread messages.

**Comment by ag91** [comment]
this exists as `slack-activity-feed-show`, needs testing so please open new issues if it doesn't work
