### ISSUE TITLE
[Feature request] slack-dashboard

### ISSUE THREAD

**Issue by cvanelteren** [emacs-slack/emacs-slack#538]
Is there a feature available to have an overview of all novel messages? Similar to the sidebar in the slack app?

**Comment by ryanprior** [comment]
There is `slack-all-unreads` which will show you all the channels with unread messages and their counts. I think a dashboard would also be nice.

**Comment by cvanelteren** [comment]
I was thinking along the lines on what `telega` has, an overview for all the unread messages not just for a specific slack-team. I now sometimes have to revert to the desktop app to regain an overview of what is said where. Especially if you are in multiple teams.

**Comment by ag91** [comment]
this exist now `slack-activity-feed-show`, please submit issues because it is not completed. Also there is `slack-all-threads`
