### ISSUE TITLE
Some emojis are not sent as emojis

### ISSUE THREAD

**Issue by Konubinix** [emacs-slack/emacs-slack#541]
When I write :+1: or run `M-x slack-insert-emoji thumbs up RET`, the slack channel gets only the characters :+1:, not the emoji.

Same for :-/, that gets replaced by the emoji in my slack buffer but not really in slack.

By chance did I miss some configuration to do so?

**Comment by ag91** [comment]
mmm, do you have emojify on? Please share your config and reopen if this is still unsolved
