### ISSUE TITLE
slack-message-show-reaction-users not automatically called in thread

### ISSUE THREAD

**Issue by skybert** [emacs-slack/emacs-slack#542]
**Describe the bug**
In a channel, putting the cursor on a message with reactions will show the reacting users in the minibuffer. This doesn't happen for thread messages.

**To Reproduce**
1. Go to a thread message
2. Add a reaction to a message
3. Put the cursor on the emoji
4. There is no info in the minibuffer on who reacted with what emoji

**Expected behavior**
A list of the reacting users along with their chosen reaction emoji is printed in the minibuffer. 

**Environment:**
 - OS: `GNU/Linux`
 - Emacs Version: `GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2020-08-28`
 - emacs-slack Version: `slack-20200830.1021`

**Comment by ag91** [comment]
this seems fixed already, I couldn't reproduce it
