### ISSUE TITLE
Error on slack-start: Failed to request slack-authorize: enterprise_is_restricted

### ISSUE THREAD

**Issue by seanw2020** [emacs-slack/emacs-slack#543]
**Describe the bug**
When I run slack-start, I get "Failed to request slack-authorize: enterprise_is_restricted"

**To Reproduce**
1. Follow the README.md at https://github.com/yuya373/emacs-slack
2. I'm using doom emacs, set `~/.doom.d/config.el` to 
```
(setq slack-buffer-emojify t) ;; if you want to enable emoji, default nil
(setq slack-prefer-current-team t)
:config
(slack-register-team
 :name "Foo"
 :default t
 :token "xoxs-foo-bar"
 :subscribed-channels '(vim)
 :full-and-display-names t)
```
3. Reload doom config (i.e., restart emacs): `C-x doom/reload`
4. M-x slack-start
5. See error "Failed to request slack-authorize: enterprise_is_restricted"

**Backtrace**
```
[2020-12-03 09:07:52] [trace] REQUEST FINISHED. URL: "https://slack.com/api/rtm.connect", PARAMS: (("mpim_aware" . "1") ("presence_sub" . "true")), DATA: (:ok :json-false :error "enterprise_is_restricted") - Foo
```

**Expected behavior**
I expected the connection to work.

**Environment:**
 - OS: macOS
 - Emacs Version: 27.1
 - emacs-slack Version: not sure -- i installed it today

**Additional context**
The Error is documented on Slack's API here: https://api.slack.com/methods/admin.apps.restrict

**Comment by sauvala** [comment]
Same here, I get the same error message.

**Comment by jo-hpe** [comment]
+1 Does this mean it would be good to have an OAuth option for emacs-slack?

**Comment by jo-hpe** [comment]
i miss having jabber

**Comment by ag91** [comment]
check the latest emacs-slack version, particularly https://github.com/emacs-slack/emacs-slack/commit/472c48673f21148d85c069e8f404584349e780ca and use `slack-refresh-token` to get instructions on how to use enterprise tokens.
Please reopen if you see still issues for these (or better open new issues!)
