### ISSUE TITLE
Error in unread.history: "unknown_method"

### ISSUE THREAD

**Issue by stonekyx** [emacs-slack/emacs-slack#546]
**Describe the bug**
Cannot open unread list with either `slack-all-unreads` or `helm-slack-unreads`.

**To Reproduce**
1. M-x slack-all-unreads, or
2. M-x helm-slack-unreads

An error will be printed in `*Messages*` saying `Error in unread.history: "unknown_method"` (for `helm-slack-unreads`) or `Failed to request slack-unread-history: unknown_method` (for `slack-all-unreads`).

**Backtrace**

**Expected behavior**
Show a list of unread conversations.

**Screenshots**

**Environment:**
 - OS: macOS
 - Emacs Version: 27.1
 - emacs-slack Version: `1f6a40f`

**Additional context**
`unread.history` API cannot be found on https://api.slack.com/methods . Seems like deprecated?

**Comment by juboba** [comment]
I'm also having this problem.

**Comment by rbugajewski** [comment]
> `unread.history` API cannot be found on https://api.slack.com/methods . Seems like deprecated?

Indeed. There’s some documentation in the message retrieval and conversation history parts, but it looks like it just gives an unread count and that you can’t see if a user read a message or not via both API endpoints.

Let’s assume that the API won’t be available in the future, what would be a viable workaround to see all unread messages?

**Comment by akoppela** [comment]
You can use `slack-select-unread-rooms` at the moment.

**Comment by ag91** [comment]
I also tried to create a `activity-buffer`, although it is not feature complete yet :P
