### ISSUE TITLE
Cannot open a single channel, got: error in process sentinel: Invalid slot type: slack-image-block-element, image-height, number, nil

### ISSUE THREAD

**Issue by dcermak** [emacs-slack/emacs-slack#548]
**Describe the bug**

I have joined the [eos design systems slack](https://slack.eosdesignsystem.com), but sadly, for about a week, I am unable to join the `#general` channel. When I select the channel via `slack-channel-select`, I only get an error message in the `*Messages*` buffer, but the channel does not open

**To Reproduce**
1. Join [eos design systems slack](https://slack.eosdesignsystem.com)
2. `M-x slack-channel-select #general`
3. See error

**Backtrace**
```
No Message in general, fetching from server...
error in process sentinel: eieio--validate-slot-value: Invalid slot type: slack-image-block-element, image-height, number, nil
error in process sentinel: Invalid slot type: slack-image-block-element, image-height, number, nil
```

**Expected behavior**

Joining `#general` should work.

**Environment:**
 - OS: Fedora 33
 - Emacs Version: 27.1
 - emacs-slack Version: `20200830.1021` (from Melpa)

**Comment by douglasdavis** [comment]
Looks like this is related to https://github.com/yuya373/emacs-slack/pull/532 The 3 line patch in that PR fixes the issue

**Comment by dcermak** [comment]
Doug Davis ***@***.***> writes:

> Looks like this is related to https://github.com/yuya373/emacs-slack/pull/532 The 3 line patch in that PR fixes the issue

I can confirm that this patch fixes my issue as well.
