### ISSUE TITLE
Not possible to invite users to channel

### ISSUE THREAD

**Issue by akoppela** [emacs-slack/emacs-slack#550]
**Describe the bug**
It's not possible to invite users to the channel. The prompt asks to select users but there is no way to go forward. E.g. how do I invite only one user? When uploading file the prompt asks to select channelt where to upload the file. There is an empty channel option which allows to go to the next step. But when inviting user there is no option to select no user to go to the next step.

**To Reproduce**
1. Call `slack-channel-invite`
2. Select a team
3. Select a channel
4. Select one user

**Expected behavior**
I would expect to have no user option to be able to go to the next step.

**Screenshots**

**Environment:**
 - OS: MacOS
 - Emacs Version: GNU Emacs 27.2 (build 1, x86_64-apple-darwin17.7.0)
 - emacs-slack Version: `20200830.1021` (melpa version)

**Comment by ag91** [comment]
different completion frameworks have different ways to provide the empty choice. M-RET for helm, please check or ask here for yours ;)
