### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by pati-ni** [emacs-slack/emacs-slack#553]
Authentication using token retrieval through the javascript console is not working:

https://github.com/wee-slack/wee-slack/issues/844

Is there any other method available?

**Comment by CommanderAsdasd** [comment]
https://github.com/yuya373/emacs-slack/pull/552
Here is doc update PR about "xoxc-" type tokens

**Comment by pati-ni** [comment]
I can confirm that the patch successfully authenticates

**Comment by pataquets** [comment]
Having the same issue, PR solved it.

**Comment by aculich** [comment]
This issue can be closed now that #552 has been merged.

**Comment by parsoj** [comment]
Having the same issue - but looking up the `d` cookie and adding it as the `:cookie` param isn't solving it for me: 

```
[2021-11-29 13:46:02] [trace] REQUEST FINISHED. URL: "https://slack.com/api/rtm.connect", PARAMS: (("mpim_aware" . "1") ("presence_sub" . "true")), DATA: (:ok :json-false :error "invalid_auth") - <company name> 
[2021-11-29 13:50:04] [error] An Error occured while closing websocket connection: (wrong-type-argument websocket nil) - <company name> 
```

**Comment by aculich** [comment]
@parsoj are you on osx? I'm having the same issue on my osx installation, but my earlier Linux installation works fine with my original patch., so I'm trying to figure out why it works in one place and not the other.

**Comment by eggcaker** [comment]
Same here , I'm on windows , it was working before with cookie d things , after update to latest master it's not working with invalid_auth

**Comment by alex-wellbelove** [comment]
Emojme is working for me, but not emacs-slack.

**Comment by parsoj** [comment]
@aculich - Sorry only just circling back on this! 

I am in fact on OSX. 
This is just a guess - but in the past I've run into some issues with some https-related c libraries that got compiled in when you built emacs on OSX/clang? 

I might poke around a bit again just to see if anything new comes up with another attempt...
