### ISSUE TITLE
Conversations list can not be updated

### ISSUE THREAD

**Issue by isamert** [emacs-slack/emacs-slack#555]
**Describe the bug**
I'm seeing bunch of `[error] request--callback: peculiar error: 429` errors in messages buffer, every 3 seconds to be exact.  I traced it and found out that the reason is the following:

```
[2021-09-02 10:41:47] [debug] Retrying Request After: 3 second, URL: https://slack.com/api/conversations.list, PARAMS: ((types . public_channel,private_channel,mpim,im) (cursor . dGVhbTpDMDFTNjBOSjZEUg==)) - ...
```

I tracked the logs and it seems like sometimes `conversations.list` returns no channels but a next cursor like the following:

```
[2021-09-02 12:32:39] [trace] REQUEST FINISHED. URL: "https://slack.com/api/conversations.list", PARAMS: (("types" . "public_channel,private_channel,mpim,im") ("cursor" . "dGVhbTpDMDFTQzVIUTQ2VA==")), DATA: (:ok t :channels nil :response_metadata (:next_cursor "dGVhbTpDMDFTQ0w0UFJRRg==")) - ...
```

Generally requesting the next cursor fails at this point and a retry loop begins. But this does not happen everytime, sometimes the next cursor request also returns an empty channel list and sometimes it returns some channels too. I'm not familar with slack's API, I don't know if this is something to be expected.

After a while, it gets into the retry loop and it becomes unable to pull all of my conversations, especially `mpim` ones. I terminated the retry loop by altering the behavior of `slack-request` on the fly and then changed `slack-conversations-list` function to only fetch for `mpim` conversations and it worked, at least for `mpim` conversations.

**To Reproduce**
I believe the core of the issue is that I'm in a very big Slack organization with quite a lot of public channels. This causes a lot of cursor traversing and after a while Slack rate-limits my calls. Even though emacs-slack complies with the `retry-after` header that is returned by slack API, it still gets 429 response or there is something wrong with what the retry-after header supposed to mean. If it means you should wait this much seconds before doing *any* call to the API, emacs-slack does not correctly implement retry-after logic. If it means you should wait this much seconds before doing a request to this particular endpoint, then this is what emacs-slack implements. [This page](https://api.slack.com/docs/rate-limits) says that it's the latter but my experiments says it's the former.

**Environment:**
 - OS: macOS
 - Emacs Version: 28
 - emacs-slack Version: Melpa 20210712.628

**Additional context**
I'm sorry that I can not give you concrete steps to reproduce the issue but as I remarked earlier it's probably related to being in a very large Slack organization. Please let me know if there is anything I can provide you to debug this issue. I got a bit familiar with how emacs-slack works internally while trying to pin down the issue.

**Comment by isamert** [comment]
For the time being, I did the following change to the `slack-conversations-list` function to exclude public channels from the results:

```diff
@@ -284,10 +284,10 @@
         (channels nil)
         (groups nil)
         (ims nil)
-        (types (or types (list "public_channel"
-                               "private_channel"
-                               "mpim"
-                               "im"))))
+        (types (or types (list 
+                          "private_channel"
+                          "mpim"
+                          "im"))))
     (cl-labels
         ((on-success
           (&key data &allow-other-keys)
```

and it works.

**Comment by dchenbecker** [comment]
I think that for larger organizations we need some sort of local store that can act as a cache for channels. The current behavior of trying to fetch/load all in memory does not seem to scale well above a couple of thousand (I have > 50000 in my org)

**Comment by ikapo** [comment]
I too am experiencing this issue die to a large number of public channels in my org.
Is there a way to only filter for specific public channels so that not all public channels are fetch?
Maybe provide an option for a channel list?

**Comment by Konubinix** [comment]
Same here...

**Comment by matthew-piziak** [comment]
@Konubinix Yeah, I feel some something's changed recently. I'm getting a lot of `Reconnecting...` and `request--callback: peculiar error: 429`.

**Comment by unhammer** [comment]
Same here, just started happening a day or two ago. Not that many channels in my list (and I do get the full list of channels up, just for some reason seeing this error message in the logs a lot).

**Comment by Konubinix** [comment]
@unhammer I experience exactly the same behavior on my side. Also, I forgot to mention that we only have 16 channels in my company, so not that many.

So far, I have to fall back to using the slack web client to make sure I don't miss important messages.

**Comment by Nazar65** [comment]
Hello there, It is now required to add cookie also tte websocket requests, it resolved the issue for me 
` (url-cookie-store "d" "xoxd-xxxxx" nil ".slack.com" "/" t)`

**Comment by unhammer** [comment]
What does that mean for multiple teams? (I tried storing the cookie of one team and it seems to have worked for all teams, but maybe I haven't tested well enough.)

Can/should `slack-register-team` just call `url-cookie-store` with the `:cookie` arg?

**Comment by Nazar65** [comment]
@unhammer The `(url-cookie-store)` will work globaly for all requests that is using `(websocket-open)` functino, so there is no way to separate them i believe, for the multiple teams probably code changes is required, to set correct cookie per team.

**Comment by Nazar65** [comment]
@unhammer or try to set both cookie, maybe incorrect one will be rejected, but need to test

**Comment by Konubinix** [comment]
@Nazar65 Awesome. I could not try it yet, and I need to deal with the fact I have several communities, but now I know what I should focus on. Thank you a lot

**Comment by ag91** [comment]
> For the time being, I did the following change to the `slack-conversations-list` function to exclude public channels from the results:

That was a smart fix. The issue can be bypassed by setting a higher limit to slack-conversations-list like [this](https://github.com/ag91/emacs-slack/commit/201a4a13e2f2c25089bedfee9e3eda2249551d3c).
It seems better than selecting only a subset of channels because it allows search functionality to still work.

**Comment by ag91** [comment]
the fixes landed in master :)
