### ISSUE TITLE
Consider adding some more contributors with permissions?

### ISSUE THREAD

**Issue by dchenbecker** [emacs-slack/emacs-slack#560]
I want to start by saying I love the module and I really appreciate all of the work you've done on it. I've noticed over the past few months that it's taking a while for some responses and I'm guessing you're pretty busy with other things. Would you consider adding a couple of other contributors with permissions to review and merge to help out with the load? I'm happy to volunteer time, and I think this would be a group that's a last resort if you're tied up with other things, unless you're interested in something more formal.

**Comment by pati-ni** [comment]
@dchenbecker are you maintaining the package as a forked repo? I am happy to get the ball rolling on that!

**Comment by smallstepman** [comment]
just a friendly ping @yuya373

**Comment by Shadesfear** [comment]
@pati-ni Any update on this?

**Comment by benthamite** [comment]
Hi @yuya373, would it be possible to add @dchenbecker and @pati-ni as contributors?

**Comment by matheusfiorin** [comment]
Hey there! Any news here, @yuya373? I'm also willing to help :)

**Comment by smallstepman** [comment]
They're very active on GitHub but choose to ignore these comments. Forking is the only reasonable solution that I can think of.
