### ISSUE TITLE
[Feature request]: Disable very disruptive error messages in minibuffer

### ISSUE THREAD

**Issue by prosoitos** [emacs-slack/emacs-slack#561]
**Describe the bug**

Not really a bug. More of a feature request.

I am getting the error messages described in #489 for some time upon booting (I imagine that the oauth process or similar takes some time). While everything actually works great, those error messages which popup for a long time by the dozens in the mini-buffer are very disruptive because the mini-buffer goes up and down each time.

The same thing happens again if I lose connection with Slack for an instant.

It would be wonderful if there were an option to disable error messages or to have them go to the \*Messages\* buffer but not popup in the minibuffer. The recent comment at the end of #489 seems to indicate that I am not the only one having this problem.

Thank you!! (and thank you for this tool 🙂).

**Screenshots**

![2022-02-02_09-44](https://user-images.githubusercontent.com/4634851/153538773-8303db0e-ee89-4e71-95e1-5045fd527836.png)

**Environment:**
 - OS: Arch Linux (5.16.8-arch1-1)
 - Emacs Version: 27.2
 - emacs-slack Version: slack-20211129.310

**Comment by prosoitos** [comment]
I guess having these error messages in the minibuffer would still be fine if they wouldn't popup with countless duplicates... It is the rapid successions of many duplicates of the same error that makes the minibuffer expand up and down and make using Emacs very uncomfortable for a while.

**Comment by prosoitos** [comment]
Turns out that, after editing my settings, I am not getting those error messages anymore... So I guess that the problem was faulty settings on my side which were not affecting functionality but were triggering those.

Not sure whether this issue should thus be closed or not.

**Comment by prosoitos** [comment]
Never mind... I am having this issue again, so it has nothing to do with my settings.

So this remains an issue.

**Comment by ag91** [comment]
I was thinking about this as well: I am planning to move all logs to a buffer or file (basically never display in the minibuffer unless user requests it). How does that sound?

**Comment by prosoitos** [comment]
That would be great!!! Thank you!

**Comment by ag91** [comment]
this was already implemented :sunny:, I just didn't see that we set as a default extra logger `slack-message-logger`.
If you want to see logs, use `slack-log-open-buffer`
