### ISSUE TITLE
`slack-log-level` isn't respected

### ISSUE THREAD

**Issue by ieure** [emacs-slack/emacs-slack#564]
**Describe the bug**
Logs contain `trace` level messages even though `slack-log-level` is set to `'info`.

**To Reproduce**
1. Eval `(setq slack-log-level 'info)`
2. Switch to the `*Slack Log - Team*` buffer.
3. Note that it contains many `trace` level ping/pong log messages.

**Backtrace**
n/a

**Expected behavior**
`trace` and `debug` level log messages shouldn't be logged.

**Screenshots**
n/a

**Environment:**
 - OS: Debian Bullssye
 - Emacs Version: 29.x.x (built from git)
 - emacs-slack Version: git ff46d88, the latest as of this writing

**Additional context**

Log message buffers are unbounded, and the excessive logging (4 messages every 10 seconds per team) causes them to become unwieldy, consume unnecessary memory, and lag Emacs.  They seem to grow at a rate of around 45mb/team/day.

**Comment by ag91** [comment]
this got into the latest version via isamert's
