### ISSUE TITLE
error when trying to kill Slack buffers

### ISSUE THREAD

**Issue by benthamite** [emacs-slack/emacs-slack#567]
**Describe the bug**
I sometimes (not always) get the following error when trying to kill an `emacs-slack` buffer:

> (wrong-type-argument hash-table-p nil)

**To Reproduce**
1. Go to an `emacs-slack` buffer.
2. Invoke `kill-this-buffer`.
3. See error

**Backtrace**
```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  remhash("D038XBDPGHW" nil)
  #f(compiled-function () #<bytecode -0x4df68c110b9f7ea>)()
  kill-this-buffer()
  funcall-interactively(kill-this-buffer)
  command-execute(kill-this-buffer record)
  execute-extended-command(nil "kill-this-buffer" "kill ")
  funcall-interactively(execute-extended-command nil "kill-this-buffer" "kill ")
  command-execute(execute-extended-command)
```

**Expected behavior**
The buffer is killed.

**Environment:**
 - OS: macOS Monterey 12.4
 - Emacs Version: GNU Emacs 28.1 (build 1, aarch64-apple-darwin21.5.0, Carbon Version 165 AppKit 2113.5) of 2022-06-01
 - emacs-slack Version: ff46d88726482211e3ac3d0b9c95dd4fdffe11c2

**Comment by jeremygooch** [comment]
I'm running into the same issue with `kill-buffer`, `kill-this-buffer` etc.
**Backtrace**
```elisp
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  remhash("C01605QLNKD" nil)
  #f(compiled-function () #<bytecode -0x11f5668a71c2d4d>)()
  kill-buffer(#<buffer *Slack - TeamName : channel-name>)
  kill-current-buffer()
  funcall-interactively(kill-current-buffer)
  call-interactively(kill-current-buffer nil nil)
  command-execute(kill-current-buffer)
```

**Environment**

- OS: macOS Ventura 13.4.1
- Emacs Version: GNU Emacs 29.0.1 (build 4, x86_64-apple-darwin22.5.0, NS appkit-2299.60 Version 13.4 (Build 22F66)) of 2023-06017
- Emacs-Slack version: 20211129.310, commit ff46d88726482211e3ac3d0b9c95dd4fdffe11c2
