### ISSUE TITLE
slack-message-remove-link-preview?

### ISSUE THREAD

**Issue by unhammer** [emacs-slack/emacs-slack#578]
**Describe the bug**
Can't find a way to remove link previews

**To Reproduce**
1. Send a message with link to website
2. Observe slack insert annoying link preview
3. `C-h a slack.*\(remove\|preview\|delete\) RET`
4. find nothing relevant

**Expected behavior**
find `slack-message-remove-link-preview`

**Environment:**
 - OS: xubuntu something
 - Emacs Version: GNU Emacs 29.0.60
 - emacs-slack Version: ff46d88726482211e3ac3d0b9c95dd4fdffe11c2

**Comment by ag91** [comment]
I wonder if we should also support a way to not see them at all, often they are more noise than not.

**Comment by ag91** [comment]
you can use `slack-remove-preview` now. There is no indication in the UX that you can do that, probably worth adding a shortcut in the readme maybe.

**Comment by prosoitos** [comment]
I am not sure how to use this function. Is there a way to permanently disable all link previews?

Thanks!

**Comment by ag91** [comment]
put your cursor on the preview and call the command, it will delete the preview (it takes the timestamp of the message and do an http call to remove the preview). That means that also the other Slack users will not see a preview anymore.

If you don't want to display preview only in emacs-slack (ie other users will still see the preview) that should be easily achievable.
If you want to automatically remove your own preview, that is possible as well I think.
I don't think it is possible to delete previews created by others.

**Comment by prosoitos** [comment]
I was thinking of disabling the previews I see on my end (I don't want to impose anything on other users and everyone should be able to chose whether or not they want to see previews). In the Slack website settings, there is such an option, but it doesn't carry over to Emacs-Slack.

In short, I just don't want to see previews because, most of the time, as you wrote above, they just really clutter things without adding much benefit

**Comment by prosoitos** [comment]
Btw, thanks for the response on how to use this function 🙂

**Comment by prosoitos** [comment]
Any way to not see the preview at all instead of having to delete it each time? (like something in the config).

Thanks!

**Comment by ag91** [comment]
@prosoitos I am not sure this commit adds exactly what you need: https://github.com/emacs-slack/emacs-slack/commit/775cd0a6ee4ddc8e83da6f1123e3c7a30d90d5af

Could you report your experience in using that please? 
I am pretty sure useful attachments will be hidden that you may want to see, but there is not an obvious way to discriminate what to hide.

**Comment by prosoitos** [comment]
Great! Thank you!!! I will test it out and report.

I am happy to have all previews hidden, so that's fine by me 🙂

**Comment by prosoitos** [comment]
I tested your suggestion for a while and it works for me. Thank you again! ❤️
