### ISSUE TITLE
How do i send a multi line message?

### ISSUE THREAD

**Issue by drewverlee** [emacs-slack/emacs-slack#579]
By multiline message, I mean something like this:

```
look at this code:
(wow)
```

When i get to "look at this code:" and i want to create a new line, but not send the message, I'm at a loss as to what to press. I can also copy and paste a multiline message into the Slack buffer.

Enter sends the message. What just creates a new line?

**Comment by matthew-piziak** [comment]
@drewverlee `C-q C-j`. 

That is, `quoted-insert` (`C-q`) followed by a newline (`C-j`).

This works across Emacs! You can use it almost everywhere you want to insert a newline without invoking Enter. For example, you can use this to insert newlines into the minibuffer.

**Comment by mankoff** [comment]
What about

```elisp
(define-key slack-mode-map (kbd "C-<return>")
  (lambda () (interactive) (insert (kbd "C-q C-j"))))
```
