### ISSUE TITLE
Can no longer connect, `[error] request--callback: peculiar error: 429`

### ISSUE THREAD

**Issue by gravieure** [emacs-slack/emacs-slack#585]
**Describe the bug**

I can no longer connect to Slack with emacs-slack.  Nothing changed on my end which would have caused this behavior.

**To Reproduce**
1. Try connecting to slack with `slack-start`.
2. Hit `C-h e` to show the `*Messages*` buffer.
3. Note that it's full of repeated messages similar to:
```
[error] request--callback: peculiar error: 429
[2023-09-21 08:07:59] [warn] [Team-Name] Reconnecting... [1/360]
```

**Expected behavior**

It should connect to Slack.

**Environment:**
 - OS: macOS Ventura 13.5.2 (22G91)
 - Emacs Version: GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.6.0, Carbon Version 165 AppKit 2113.6)
 - emacs-slack Version: @ff46d88, latest commit in this repo at the time of this writing.

**Additional context**

HTTP status 429 is sent to clients when they exceed rate limits, which implies that either emacs-slack is failing to adhere to them, or perhaps Slack has noticed it and decided to block connections by lying to me.

Alternate theory: I've noticed for some time that emacs-slack would get some 429 responses when connecting, but it would eventually (after 2-3 attempts) succeed and start working.  Perhaps I have a large number of channels or DMs open, and it's connecting, but the initial state is large, and emacs-slack doesn't rate limit those, so it fails immediately.

**Comment by JasonSKK** [comment]
Same problem here, no changes in my config

**Comment by seblemaguer** [comment]
@JasonSKK and @gravieure the solution is discussed in the issue #584, especially at this post https://github.com/yuya373/emacs-slack/issues/584#issuecomment-1728326996

**Comment by JasonSKK** [comment]
Thanks. 
I have tried that however, I am getting:
[2023-09-22 09:42:24] [error] [WORKSPACE] An Error occured while closing websocket connection: (wrong-type-argument websocket nil)

websocket is installed
and #553 workaround doesn't do it for me.

**Comment by gravieure** [comment]
> @JasonSKK and @gravieure the solution is discussed in the issue #584, especially at this post [#584 (comment)](https://github.com/yuya373/emacs-slack/issues/584#issuecomment-1728326996)

Thank you for the pointer, however, I'm experiencing a different problem.  #584 is a 401 error trying to connect, while I'm getting a 429, which is typically used when a client exceeds the server rate limit.  I pulled the jumper047/emacs-slack fork, and it doesn't work -- I still get 429 errors when I connect.

**Comment by gravieure** [comment]
> So emacs-slack should rate-limit itself / pause a bit between each fetch?

I believe this is likely the root of the issue.

Either that, or Slack fingerprints the client and returns a false 429 for unofficial ones.

**Comment by isamert** [comment]
> So emacs-slack should rate-limit itself / pause a bit between each fetch?
I have implemented a poor-man version of such thing in my fork, see this:
https://github.com/isamert/emacs-slack/blob/master/slack-conversations.el#L287-L337

I also have other stuff in my fork that is kind of special to my use-case where I disabled emoji downloads etc. to make connection smoother and it kinda works okay. Sometimes I run into issues but restarting emacs-slack works because connection goes smoothly.

**Comment by seblemaguer** [comment]
After few weeks, I confirm that it works for me

**Comment by ag91** [comment]
[this](https://github.com/ag91/emacs-slack/commit/b710c9c4ea8d0c47c41675be345d800c5684316a) has worked for me and others: please reopen if you still see issues with the latest version of emacs-slack (hopefully not!)

Ah and make sure to have `d-s` and `lc` cookies, please follow `slack-refresh-token` instructions in the buffer that command opens.
