### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by pati-ni** [emacs-slack/emacs-slack#589]
Hi @yuya373, I was wondering if this package is deprecated? To my [understanding](https://stackoverflow.com/q/62759949/4864088) xoxc are deprecated and as of now emacs slack hangs.

Is there an alternative way to access the API and use slack through emacs?

**Comment by unhammer** [comment]
See https://github.com/yuya373/emacs-slack/issues/585#issuecomment-1985735967 – that fork works fine.

**Comment by pati-ni** [comment]
@unhammer Thanks, any idea how to retrieve these tokens using the slack API or some active slack session?

**Comment by unhammer** [comment]
https://my.slack.com/customize and F12→Storage→Cookies on Firefox, more info at
 https://github.com/wee-slack/wee-slack?tab=readme-ov-file#get-a-session-token

**Comment by ag91** [comment]
just a note: I joined as a new maintainer of this repository.
I am just waiting a day or so for a confirmation I can pull a bunch of commits from another fork and most of the PRs and a good number of issues will be solved.

**Comment by ag91** [comment]
un-depreacated :) https://github.com/emacs-slack/emacs-slack/commit/4aa670b992debd1bd16d1bda649d61458fc77249
