### ISSUE TITLE
Open url?

### ISSUE THREAD

**Issue by unhammer** [emacs-slack/emacs-slack#590]
It would be nice if there were a way to open a slack conversation from a slack url, e.g. if you get an email with `View in the archives:
https://foo.slack.com/x-p233-90406-69742/archives/D0434N/p14879`  then `slack-open-url` puts you in that conversation

**Comment by ag91** [comment]
this is available now ([here the code](https://github.com/ag91/emacs-slack/blob/master/slack-room-buffer.el#L363))
